# Generated by Django 6.0.6 on 2026-06-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='usename',
            new_name='username',
        ),
    ]
