# Generated by Django 6.0.6 on 2026-06-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory_name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slud',
            new_name='slug',
        ),
    ]
